apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-depl
  labels:
    app: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
        - name: airflow-container
          image: puckel/docker-airflow
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-srv
  labels:
    app: airflow
spec:
  type: NodePort
  selector:
    app: airflow
  ports:
    - name: airflow-port
      port: 8080
      targetPort: 8080