apiVersion: apps/v1
kind: Deployment
metadata:
    name: superset-depl
    labels:
        app: superset
spec:
    replicas: 1
    selector:
        matchLabels:
            app: superset
    template:
        metadata:
            labels:
              app: superset
        spec:
            containers:
              - name: superset
                image: amancevice/superset
                # ports:
                #     - containerPort: 8088
                env:
                    - name: SUPERSET_LOAD_EXAMPLES
                      value: "true"
---
apiVersion: v1
kind: Service
metadata:
    name: superset-srv
    labels:
      app: superset
spec:
    type: NodePort
    selector:
        app: superset
    ports:
        - port: 8088
          targetPort: 8088